### ISSUE TITLE
레이아웃 개선

### ISSUE THREAD

**Issue by jsh1147** [Step3-kakao-tech-campus/Team18_FE#17]
## Description

개발이 진행됨에 따라 로그인 및 api 기능이 구체화되므로,
임시로 설정했던 데이터에 대해 실제 구현을 진행함

## TO-DO

- [x] GNB 계정 상태 관련 로직 수정
- [x] AuthCheck 계정 상태 관련 로직 수정
- [x] TEST 버튼 제거
- [x] 프로필 이미지 API 구현
