### ISSUE TITLE
레이아웃 구현

### ISSUE THREAD

**Issue by jsh1147** [Step3-kakao-tech-campus/Team18_FE#3]
## Description

GNB와 Footer로 구성된 레이아웃을 구현

## TO-DO

- [x] 레이아웃 구조 작성
- [x] 레이아웃 로직 구현
- [x] 레이아웃 CSS 적용
- [x] 계정 관련 로직 적용

## ETC

로그인/로그아웃 버튼, 프로필 사진, Auth 확인 등은 Account와 연계되므로
Account 확립 전에는 Mock 객체를 사용하거나 임시 로직으로 대체해야 함
