### ISSUE TITLE
오픈채널 채팅 구현 

### ISSUE THREAD

**Issue by bada308** [Step3-kakao-tech-campus/Team18_FE#30]
## Description

Sendbird API를 이용해 오픈 채널 채팅방을 구현한다.

## TO-DO

- [ ] Open Channel 추가 기능 구현
- [ ] Open Channel List UI 수정
- [ ] 유저 이름/ 닉네임 연결 구현
