### ISSUE TITLE
사용자 정보 및 인가 api 통신 

### ISSUE THREAD

**Issue by chaemina** [Step3-kakao-tech-campus/Team18_FE#43]
## Description

사용자 정보 및 인증 api 통신 
- 사용자 정보의 경우, userAtom 전역 상태로 관리 하려 했으나
(1) 새로고침 시 초기화 됨 -> 다른 페이지에서 정보 활용 불가 
(2) 로컬 스토리지에 저장 -> 명시적으로 로그아웃 하지 않은 경우 삭제 불가, 보안 문제 

**사용자 식별(정보)api**에 정보가 필요한 페이지에서 그때 그때 GET 요청 으로 받아서 사용하기로 함 
- 현재까지 필요한 사용자 식별 정보 : 이름, 이메일, 프로필 이미지 

## TO-DO

- [x] Backend api axios로 통신
- [x] 회원가입 시 사용자 정보 POST 요청(이름, 이메일, 비번, 나이, 연락처, 역할 , 관심사, 국가 / 소개말, 프로필 이미지 null)
- [x] 회원 가입 시 이메일 중복 체크 기능 구현 
- [x] 회원 가입 폼 수정  : 사용자 정보 입력란 추가 (age, phone) , 관심사 선택 컴포넌트 추가 
- [x] 로그인 시 **요청** 이메일, 패스워드 / **응답**  토큰 - 로컬 스토리지에 저장
