### ISSUE TITLE
채팅 기능 구현

### ISSUE THREAD

**Issue by bada308** [Step3-kakao-tech-campus/Team18_FE#46]
## Description
채널 리스트 기능 구현
채널 생성 기능 구현
채팅 메세지 기능 구현

{이슈 설명}

## TO-DO

- [x] 채널 리스트 기능 구현
    - [x] 채널 리스트 Item 컴포넌트 구현
         - 채널 이름, 이미지, 설명, 참여자 수 렌더링
    - [x] Public 채널 리스트 구현
        - 모든 채널
    - [x] Public 채널 `참여` 클릭 시 해당 채널에 참여 
    - [x] Joined 채널 리스트 구현
        - 유저가 참여한 채널
    - [x] Joined 채널 `trash icon` 클릭 시 해당 채널 나가기
    - [x] Joined 채널 아이템 클릭 시 해당 채널 채팅방 페이지로 이동
- [x] 채널 생성 기능 구현
     - [x] 채널 생성 모달창 컴포넌트 구현
     - [x] 이름, 이미지, 설명 입력 후 버튼 클릭 시 채널 생성
- [x] 채팅 메세지 기능 구현
    - [x] 해당 채널 메세지 조회 기능 구현
    - [x] Sent 컴포넌트
        - 현재 유저가 보낸 메세지 / 이미지 렌더링 ❌
    - [x] Received 컴포넌트 구현
         - 다른 유저가 보낸 메세지 / 이미지 렌더링 ✅
    - [x] 메세지 보내기 기능 구현
