### ISSUE TITLE
채팅 세부 기능 구현

### ISSUE THREAD

**Issue by bada308** [Step3-kakao-tech-campus/Team18_FE#54]
## Description

채팅 세부 기능을 구현한다.

## TO-DO

- [x] Public Channel List Item 클릭 시 Channel Detail 모달 출력
- [x] Channel Detail 페이지 구현
- [x] 태그 기능 구현
- [x] 페이지 수정 기능 구현 (Channel Owner만 가능)
- [ ] 로그인 기능 연결
- [x] 에러 코드 상수화
- [x] 채널 리스트 무한스크롤 적용
- [ ] 채팅 메세지 무한스크롤 적용
- [x] 검색 기능 구현
