### ISSUE TITLE
마이 페이지 구현 

### ISSUE THREAD

**Issue by chaemina** [Step3-kakao-tech-campus/Team18_FE#56]
## Description

사용자 정보를 확인 및 수정 하는 마이페이지를 구현한다. 

## TO-DO

- [x] 사용자의 프로필 조회 페이지 
- [x] 사용자의 개인정보 조회 페이지 
- [x] 사용자의 개인정보 수정 페이지 

## ETC

1. 기존의 라우터는 모두 id 파라미터를 사용했으나 -> 프로필 페이지만 다른 사용자가 조회 가능하고 다른 페이지는 인증된 사용자만 정보 조회가 가능 해야하기에 mypage/information, mypage/information/fix 로 변경함.  userInfo api 요청 도 헤더에 토큰을 담아 /profile로 요청 보냄 
2. 프로필 수정 페이지와 개인정보 수정 페이지는 중복되는 기능이라 판단하여, 프로필 수정 페이지를 삭제함
