### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by chaemina** [Step3-kakao-tech-campus/Team18_FE#59]
## Description

멘토님 코드리뷰 기반 및 후순위 리팩토링 

## TO-DO

- [x] 버튼 컴포넌트 hover 적용 
- [x] 개인정보 수정 페이지에서 사용자 프로필 이미지 등록
- [ ] 미들웨어로 서버에 사용자 정보(이름, 이메일, 프로필 이미지) 요청을 전역 상태로 관리
- [x] 로그인 실패 에러 처리 -> UI 
- [ ] GNB 반응형 구현 
- [ ] 회원 가입 성공 페이지 생성
- [x] profile fix page-> 라우터 자체에 접근 할 순 없도록 -> information form 으로 리다이렉트 하거나, 모달 띄우기 

## ETC

1. token, auth의 전역 상태 로컬 스토리지에서 꺼내오는 값으로 초기화 -> 2번의 동작이 발생해서 전역상태로 관리하는 것보다 바로 로컬스토리지에서 꺼내 쓰는 것이 효율적 
2. 사용자 정보의 경우 전역 상태로 관리하면 새로 고침 시 초기화되고, 로컬 스토리지에 저장하는 것은 보안적으로 좋지 않음 -> 필요할 때마다 백앤드에 getUser/ api 요청으로 사용자의 이름, 이메일, 프로필 이미지 정보를 받음 

-> 전역 상태가 사용되지 않고 있음. 제거하거나 미들웨어로 서버에 사용자 정보 요청을 전역 상태로 관리 !
