### ISSUE TITLE
백앤드 api 연결 

### ISSUE THREAD

**Issue by chaemina** [Step3-kakao-tech-campus/Team18_FE#67]
## Description

백앤드 api 연결 

## TO-DO

- [x] 개인 정보 수정 시 password check/ api 요청(post+ token) 로 사용자 인증 
- [x] videos/main api 작성 (url param :categoryid, page) 
- [x] 액세스 토큰 만료 오류 -> users/refresh 요청 

**api 연결** 
- [x] videos/main  (응답 데이터 페이지별로 오도록 수정 확인 필요)
- [x] videos/interest (토큰 만료 시 오류 메세지 수정 확인 필요)
- [x] videos/history 
- [x] videos/:id
- [x] profiles/simple
- [x] profiles/fix
