### ISSUE TITLE
공통 컴포넌트 구현

### ISSUE THREAD

**Issue by bada308** [Step3-kakao-tech-campus/Team18_FE#7]
## Description
공통 컴포넌트 구현

## TO-DO
- [x] tailwind 색상 커스텀
- [x] Noto Sans 폰트 적용
- [x] Button 컴포넌트 구현
- [x] Label 컴포넌트 구현
- [x] Dropdown 컴포넌트 구현
- [x] 외부 클릭 감지 Hook 구현

## ETC
Dropdown option 변경 시 실행되는 handle 함수는 api 연결 시 수정이 필요함
